# Generated by Django 4.1.2 on 2023-10-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_alter_album_table_alter_musician_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table=None,
        ),
        migrations.AlterModelTable(
            name='musician',
            table=None,
        ),
    ]
